const fighters = [
    {
        "name": "Persival2",
        "id": 4,
        "img": "https://cryptogalaxy.online/ships/fighters/persival.webp",
        "mp": 2,
        "hash": "",
        "date": "",
        "owner": "Game",
        "onSell": true,
        "sellPrice": "0.1",
        "energy": 2,
        "shield": 185,
        "damage": 100,
        "type":"Fighter",
        "subType":"T1",
        "charge":0,
        "attack":95
    },
    {
        "name": "JackSaw",
        "id": 5,
        "img": "https://cryptogalaxy.online/ships/fighters/jacksaw.webp",
        "mp": 4,
        "hash": "",
        "date": "",
        "owner": "Game",
        "onSell": true,
        "sellPrice": "0.2",
        "energy": 2,
        "shield": 385,
        "damage": 100,
        "type":"Fighter",
        "subType":"T2",
        "charge":0,
        "attack":280
    },
    {
        "name": "Pelican",
        "id": 6,
        "img": "https://cryptogalaxy.online/ships/fighters/pelican.webp",
        "mp": 8,
        "hash": "",
        "date": "",
        "owner": "Game",
        "onSell": true,
        "sellPrice": "0.35",
        "energy": 2,
        "shield": 1450,
        "damage": 100,
        "type":"Fighter",
        "subType":"T3",
        "charge":0,
        "attack":780
    },
    {
        "name": "Hell",
        "id": 7,
        "img": "https://cryptogalaxy.online/ships/fighters/hell.webp",
        "mp": 12,
        "hash": "",
        "date": "",
        "owner": "Game",
        "onSell": true,
        "sellPrice": "0.5",
        "energy": 2,
        "shield": 4020,
        "damage": 100,
        "type":"Fighter",
        "subType":"T4",
        "charge":0,
        "attack":1920
    },
    

]

export default fighters